services:
  web:
    build: .
    container_name: django_web
    command: gunicorn resume_project.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: resume_caddy
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./deploy/Caddyfile:/etc/caddy/Caddyfile:ro

      # مهم
      - static_volume:/srv/static:ro
      - media_volume:/srv/media:ro

    environment:
      - DOMAIN=${DOMAIN}
      - CADDY_EMAIL=${CADDY_EMAIL}

    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
  caddy_data:
  caddy_config: