# Generated by Django 6.1 on 2026-08-07 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careergoal',
            options={'verbose_name': '🎯 Career Goal', 'verbose_name_plural': '🎯 Career Goal'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order', '-start_date'], 'verbose_name': '🎓 Education', 'verbose_name_plural': '🎓 Education'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order', '-start_date'], 'verbose_name': '💼 Experience', 'verbose_name_plural': '💼 Experiences'},
        ),
        migrations.AlterModelOptions(
            name='experiencebullet',
            options={'ordering': ['order'], 'verbose_name': '📌 Experience Bullet', 'verbose_name_plural': '📌 Experience Bullets'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['order'], 'verbose_name': '🌐 Language', 'verbose_name_plural': '🌐 Languages'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '👤 Profile', 'verbose_name_plural': '👤 Profile'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at'], 'verbose_name': '🚀 Project', 'verbose_name_plural': '🚀 Projects'},
        ),
        migrations.AlterModelOptions(
            name='projecttag',
            options={'verbose_name': '🏷️ Project Tag', 'verbose_name_plural': '🏷️ Project Tags'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'name'], 'verbose_name': '💻 Skill', 'verbose_name_plural': '💻 Skills'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telegram_url',
        ),
        migrations.AlterField(
            model_name='careergoal',
            name='description',
            field=models.TextField(help_text='می\u200cتونی از HTML استفاده کنی (مثلاً لینک)'),
        ),
        migrations.AlterField(
            model_name='careergoal',
            name='icon',
            field=models.CharField(choices=[('fa-robot', '🤖 Robot'), ('fa-brain', '🧠 Brain'), ('fa-rocket', '🚀 Rocket'), ('fa-star', '⭐ Star'), ('fa-lightbulb', '💡 Lightbulb'), ('fa-fire', '🔥 Fire'), ('fa-bullseye', '🎯 Target'), ('fa-gem', '💎 Gem')], default='fa-robot', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='عکس پروفایل - فرمت JPG یا PNG - سایز مربعی (مثلاً 500x500)', null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(help_text='لینک گیت\u200cهاب پروژه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='icon_class',
            field=models.CharField(choices=[('fa-code', '💻 Code'), ('fa-laptop-code', '🖥️ Laptop Code'), ('fa-globe', '🌐 Globe'), ('fa-server', '🖧 Server'), ('fa-database', '🗄️ Database'), ('fa-cloud', '☁️ Cloud'), ('fa-calendar-check', '📅 Calendar'), ('fa-tasks', '✅ Tasks'), ('fa-shopping-cart', '🛒 Shopping Cart'), ('fa-shopping-bag', '🛍️ Shopping Bag'), ('fa-store', '🏪 Store'), ('fa-robot', '🤖 Robot/AI'), ('fa-brain', '🧠 Brain/ML'), ('fa-chart-line', '📈 Chart'), ('fa-chart-bar', '📊 Bar Chart'), ('fa-chart-pie', '🥧 Pie Chart'), ('fa-comments', '💬 Chat'), ('fa-comment-dots', '🗨️ Comment'), ('fa-envelope', '✉️ Email'), ('fa-bell', '🔔 Notification'), ('fa-camera', '📷 Camera'), ('fa-image', '🖼️ Image'), ('fa-video', '🎬 Video'), ('fa-music', '🎵 Music'), ('fa-cloud-sun', '⛅ Weather'), ('fa-map-marker-alt', '📍 Map'), ('fa-map', '🗺️ Map 2'), ('fa-shield-alt', '🛡️ Security'), ('fa-lock', '🔒 Lock'), ('fa-key', '🔑 Key'), ('fa-gamepad', '🎮 Game'), ('fa-chess', '♟️ Chess'), ('fa-heartbeat', '❤️ Health'), ('fa-stethoscope', '🩺 Medical'), ('fa-cogs', '⚙️ Settings'), ('fa-tools', '🔧 Tools'), ('fa-magic', '✨ Magic'), ('fa-bolt', '⚡ Fast'), ('fa-fire', '🔥 Hot'), ('fa-mobile-alt', '📱 Mobile'), ('fa-desktop', '🖥️ Desktop')], default='fa-code', help_text='آیکون پروژه - با ایموجی انتخاب کن', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('advanced', '🟢 Advanced'), ('intermediate', '🔵 Intermediate'), ('beginner', '🟡 Beginner')], default='intermediate', max_length=20),
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم نمایشی (مثلاً: GitHub)', max_length=50)),
                ('url', models.URLField(help_text='لینک کامل (مثلاً: https://github.com/username)')),
                ('icon_class', models.CharField(choices=[('fab fa-github', 'GitHub'), ('fab fa-linkedin-in', 'LinkedIn'), ('fab fa-telegram-plane', 'Telegram'), ('fab fa-whatsapp', 'WhatsApp'), ('fab fa-instagram', 'Instagram'), ('fab fa-x-twitter', 'Twitter/X'), ('fab fa-youtube', 'YouTube'), ('fab fa-discord', 'Discord'), ('fab fa-stack-overflow', 'Stack Overflow'), ('fab fa-gitlab', 'GitLab'), ('fab fa-medium', 'Medium'), ('fab fa-dev', 'Dev.to'), ('fab fa-dribbble', 'Dribbble'), ('fab fa-behance', 'Behance'), ('fab fa-codepen', 'CodePen'), ('fas fa-envelope', 'Email'), ('fas fa-globe', 'Website'), ('fas fa-blog', 'Blog')], default='fab fa-github', help_text='آیکون فونت\u200cآسام', max_length=50)),
                ('show_tooltip', models.BooleanField(default=False, help_text='متن راهنما نشون بده؟ (مثل آیدی تلگرام)')),
                ('tooltip_text', models.CharField(blank=True, help_text='متن راهنما (مثلاً: @my_id)', max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='resume_app.profile')),
            ],
            options={
                'verbose_name': '🔗 Social Media',
                'verbose_name_plural': '🔗 Social Media Links',
                'ordering': ['order', 'name'],
            },
        ),
    ]
