# Generated by Django 6.1 on 2026-08-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_alter_careergoal_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام بکاپ (خودکار تولید میشود)', max_length=200)),
                ('backup_file', models.FileField(blank=True, help_text='فایل بکاپ SQLite', null=True, upload_to='backups/')),
                ('backup_size', models.PositiveIntegerField(default=0, help_text='حجم فایل (بایت)')),
                ('status', models.CharField(choices=[('success', '✅ Success'), ('failed', '❌ Failed'), ('processing', '⏳ Processing')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_automatic', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SQLite Backup',
                'verbose_name_plural': 'SQLite Backups',
                'ordering': ['-created_at'],
            },
        ),
    ]
